### ISSUE TITLE
GPLv3 licence conflicts with the usage of this library

### ISSUE THREAD

**Issue by barkermn01** [tsunamods-codes/the-test-room#1]
The full version of GPLv3 is not permissible for the TEX format, which is proprietary but does have open licensing for use. However, any license that is not GPLv3 directly conflicts with it. It should be a Lesser GPL or another license that does not have the 'infectivity' of GPLv3.

Due to the clause stating "All code linked with GPL 3.0 source code must be disclosed under a GPL 3.0 compatible license," the term 'linked' is overly broad and includes usage. Since the TEX format is proprietary, and the texture format for FF7 uses a specific form of TEX, there are restrictions on it's usage, including the fact that the source code for the parser is not open source.

This presents a significant issue. A Lesser GPL would be preferable because it would not extend the 'infectivity' to users of unmodified versions of other libraries. Alternatively, another open license that is not infectious could be used. As it stands, using this requires 7th Heaven to inject into the game. If the game uses a GPLv3 library (in this case, an asset library) and the game itself is not GPLv3, it would not be permitted to use this library, thus violating the GPLv3. The LGPLv3 might be acceptable, or in the worst case, the LGPLv2, which is definitely safe.

**Comment by julianxhokaxhiu** [comment]
Thanks @barkermn01 for rising this up. With one would you suggest? `LGPLv3` or `LGPLv2`? Is it safe to go with the first?

**Comment by barkermn01** [comment]
Both should be good so you should be able to use the LGPLv3 i personally prefer BSD for this stuff just because it stops all these problems but then it allowed people to use the work in there own work without sharing there modification if you don't want that then a LGPLv3 should be good to use.

**Comment by julianxhokaxhiu** [comment]
Done, committed the change and now the repository uses LGPL-3.0 :) Thank you!
